services:
  - type: web
    name: academico-backend
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        value: mysql://root:pcIkzbgLARWToWjeXnSinSuvscCfjeEM@metro.proxy.rlwy.net:52872/railway
      - key: JWT_SECRET
        value: academico2024secreto
      - key: PORT
        value: 4000
      - key: ALLOWED_ORIGINS
        value: https://academico-platform.vercel.app
      - key: NODE_ENV
        value: production
    repo: https://github.com/Felquiroz/academico-platform
    branch: main
    rootDirectory: backend